### ISSUE TITLE
Problem with "Projects" section 

### ISSUE THREAD

**Issue by mo7ammedmostafa** [bamos/cv#24]
It would seem that the projects section in cv.yaml template has been deprecated since there is no projects.tex template available 
So how do I add the projects section?,  I am not sure what is the new alternative?  or should I come up with my own template?
Thanks for the awesome cv generator 
Regards,
Kamra

**Comment by bamos** [comment]
Sorry about the delays here but yes, you can write a custom template to render a projects section in the YAML that would need to be correctly connected into `generate.py`
