### ISSUE TITLE
ImportError: cannot import name 'soft_unicode' from 'markupsafe'

### ISSUE THREAD

**Issue by albertux** [bamos/cv#26]
$ make
 ImportError: cannot import name 'soft_unicode' from 'markupsafe'
make: *** [Makefile:35: build/cv.tex] Error 1

**Comment by albertux** [comment]
pip3 install markupsafe==2.0.1 

This will fix the problem ^ maybe will be worth to update requirements.txt

**Comment by bamos** [comment]
Thanks, added!
